-- =============================================================================
-- GigCircle Cooperative Gig/Service Marketplace Platform
-- Production PostgreSQL Schema for Supabase
-- Target Database: Supabase PostgreSQL (PostgreSQL 14+)
-- Codebase Audit Date: 2026-09-08
-- =============================================================================

-- 1. EXTENSION DECLARATIONS
-- Enable pgcrypto for cryptographic functions if needed by PostgreSQL
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Enable uuid-ossp for UUID generation support if required in future migrations
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. LEGACY CONSTRAINT CLEANUP (Ref: DatabaseMigrationRunner.java)
-- Ensures backward compatibility with legacy database instances if updating existing schemas
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'jobs') THEN
        ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_status_check;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'notifications') THEN
        ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
    END IF;
END $$;

-- 3. MAIN TABLES

-- -----------------------------------------------------------------------------
-- Table: users
-- Represents platform users: Customers, Workers, and Admins.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('CUSTOMER', 'WORKER', 'ADMIN')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Table: worker_profiles
-- Detailed worker profile parameters, rate, location, and availability.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS worker_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL UNIQUE,
    bio VARCHAR(500),
    experience_years INTEGER NOT NULL CHECK (experience_years >= 0),
    hourly_rate NUMERIC(10, 2) NOT NULL CHECK (hourly_rate >= 0),
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    service_location VARCHAR(255),
    service_radius_km INTEGER CHECK (service_radius_km IS NULL OR service_radius_km >= 0),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(500),
    city VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_worker_profiles_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: worker_profile_skills (Collection Table)
-- Element collection storing skill tags for each worker profile.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS worker_profile_skills (
    worker_profile_id BIGINT NOT NULL,
    skill VARCHAR(255) NOT NULL,
    CONSTRAINT fk_worker_profile_skills_profile FOREIGN KEY (worker_profile_id) REFERENCES worker_profiles (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: worker_profile_categories (Collection Table)
-- Element collection storing service category enums for each worker profile.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS worker_profile_categories (
    worker_profile_id BIGINT NOT NULL,
    category VARCHAR(255) NOT NULL CHECK (category IN (
        'PLUMBING', 'ELECTRICAL', 'CLEANING', 'CARPENTRY', 
        'APPLIANCE_REPAIR', 'PAINTING', 'GARDENING', 'OTHER'
    )),
    CONSTRAINT fk_worker_profile_categories_profile FOREIGN KEY (worker_profile_id) REFERENCES worker_profiles (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: service_requests
-- Customer-created gig requests detailing budget, location, and category.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    category VARCHAR(255) NOT NULL CHECK (category IN (
        'PLUMBING', 'ELECTRICAL', 'CLEANING', 'CARPENTRY', 
        'APPLIANCE_REPAIR', 'PAINTING', 'GARDENING', 'OTHER'
    )),
    description VARCHAR(1000) NOT NULL,
    location VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(500),
    city VARCHAR(100),
    budget NUMERIC(10, 2) NOT NULL CHECK (budget >= 0),
    preferred_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CANCELLED')),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_requests_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: jobs
-- Active and historical job assignments mapping service requests to workers.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT NOT NULL UNIQUE,
    worker_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'ACCEPTED' CHECK (status IN (
        'OPEN', 'ACCEPTED', 'IN_PROGRESS', 'PAYMENT_REQUIRED', 'COMPLETED', 'DECLINED'
    )),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP WITHOUT TIME ZONE,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_jobs_service_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_jobs_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: payments
-- Financial transaction records, platform fees, payment gates, and refunds.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    service_amount NUMERIC(12, 2) NOT NULL CHECK (service_amount >= 0),
    platform_fee NUMERIC(12, 2) NOT NULL CHECK (platform_fee >= 0),
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    payment_method VARCHAR(255) NOT NULL CHECK (payment_method IN ('UPI', 'CARD', 'CASH')),
    payment_method_details VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN (
        'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED'
    )),
    transaction_reference VARCHAR(64) NOT NULL UNIQUE,
    paid_at TIMESTAMP WITHOUT TIME ZONE,
    failure_reason VARCHAR(500),
    refund_amount NUMERIC(12, 2) CHECK (refund_amount IS NULL OR refund_amount >= 0),
    refunded_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: ratings
-- Reviews and star ratings (1 to 5) submitted by customers upon job completion.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,
    score INTEGER NOT NULL CHECK (score >= 1 AND score <= 5),
    review VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ratings_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: notifications
-- User notifications for system alerts, job lifecycle events, and payments.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL CHECK (type IN (
        'SERVICE_REQUEST_CREATED', 'WORKER_ASSIGNED', 'JOB_STARTED', 'JOB_COMPLETED',
        'RATING_RECEIVED', 'EARNING_GENERATED', 'SERVICE_REQUEST_CANCELLED',
        'WORKER_ACTIVATED', 'WORKER_DEACTIVATED', 'NEW_WORKER_REGISTERED',
        'WORKER_DECLINED_JOB', 'LOW_WORKER_RATING', 'LEDGER_ERROR', 'SYSTEM_ERROR',
        'PAYMENT_REQUIRED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'PAYMENT_REFUNDED'
    )),
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: earnings
-- Worker earnings ledger records generated upon job payment completion.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS earnings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    worker_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL CHECK (gross_amount >= 0),
    platform_fee NUMERIC(12, 2) NOT NULL CHECK (platform_fee >= 0),
    worker_earning NUMERIC(12, 2) NOT NULL CHECK (worker_earning >= 0),
    fee_percentage NUMERIC(5, 2) NOT NULL CHECK (fee_percentage >= 0),
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'AVAILABLE')),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    available_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_earnings_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_earnings_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_earnings_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: admin_activity
-- Audit trail of administrative actions across users, jobs, and system entities.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    actor_role VARCHAR(255) NOT NULL CHECK (actor_role IN ('CUSTOMER', 'WORKER', 'ADMIN')),
    action_type VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id BIGINT,
    description VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. INDEXES

-- Explicit JPA Indexes from @Table annotations
CREATE INDEX IF NOT EXISTS idx_payments_job_id ON payments(job_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer_id ON payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_txn_ref ON payments(transaction_reference);

CREATE INDEX IF NOT EXISTS idx_noti_recipient ON notifications(recipient_id);
CREATE INDEX IF NOT EXISTS idx_noti_read ON notifications(read);
CREATE INDEX IF NOT EXISTS idx_noti_created_at ON notifications(created_at);

CREATE INDEX IF NOT EXISTS idx_admin_activity_created_at ON admin_activity(created_at);
CREATE INDEX IF NOT EXISTS idx_admin_activity_actor_user_id ON admin_activity(actor_user_id);

-- Foreign key & Performance lookup indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_worker_profiles_worker_id ON worker_profiles(worker_id);
CREATE INDEX IF NOT EXISTS idx_worker_profile_skills_wp_id ON worker_profile_skills(worker_profile_id);
CREATE INDEX IF NOT EXISTS idx_worker_profile_categories_wp_id ON worker_profile_categories(worker_profile_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_customer_id ON service_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_status ON service_requests(status);
CREATE INDEX IF NOT EXISTS idx_jobs_service_request_id ON jobs(service_request_id);
CREATE INDEX IF NOT EXISTS idx_jobs_worker_id ON jobs(worker_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_ratings_customer_id ON ratings(customer_id);
CREATE INDEX IF NOT EXISTS idx_ratings_worker_id ON ratings(worker_id);
CREATE INDEX IF NOT EXISTS idx_earnings_worker_id ON earnings(worker_id);
CREATE INDEX IF NOT EXISTS idx_earnings_customer_id ON earnings(customer_id);

-- 5. DEFAULT INITIAL REFERENCE DATA
-- Optional: Bootstrap default admin user if missing (matches AdminBootstrapRunner logic)
-- Note: BCrypt hash for default password 'AdminPass123!'
INSERT INTO users (name, email, phone, password, role, active, created_at, updated_at)
VALUES (
    'System Admin',
    'admin@gigcircle.com',
    '0000000000',
    '$2a$10$eD8.s15e8qJvD/T/O8eS4eU59aW2sZ3m9R5C5N8P0Q5R6S7T8U9V.',
    'ADMIN',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (email) DO NOTHING;

-- End of schema.sql
