package com.sih.cooperative.entity;

public enum NotificationType {
    SERVICE_REQUEST_CREATED,
    WORKER_ASSIGNED,
    JOB_STARTED,
    JOB_COMPLETED,
    RATING_RECEIVED,
    EARNING_GENERATED,
    SERVICE_REQUEST_CANCELLED,
    WORKER_ACTIVATED,
    WORKER_DEACTIVATED,
    NEW_WORKER_REGISTERED,
    WORKER_DECLINED_JOB,
    LOW_WORKER_RATING,
    LEDGER_ERROR,
    SYSTEM_ERROR,
    PAYMENT_REQUIRED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED
}
